### ISSUE TITLE
unable to `npm run build` successfully: missing icon file

### ISSUE THREAD

**Issue by bahtou** [scrapd/scrapdviz#32]
Issue Type
----------
- Bug report

Current Behavior
----------------
`npm run build` launches the build process but fails

Expected Behavior
-----------------
`npm run build` to finish successfully

Possible Solution
-----------------
Add missing icon?

Steps to Reproduce
------------------
1. run `npm run build` on the command line

**Comment by bahtou** [comment]
```
$ npm run build

> scrapdviz@0.1.0 build
> next build

Creating an optimized production build ...

(node:7840) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
> Using external babel configuration
> Location: "/scrapdviz/package.json"
/scrapdviz/node_modules/webpack-pwa-manifest/dist/icons/index.js:128
      if (err) throw new _IconError2.default('It was not possible to read \'' + icon.src + '\'.');
               ^

Error: It was not possible to read '/scrapdviz/static/manifest/icon.png'.
    at new IconError (/scrapdviz/node_modules/webpack-pwa-manifest/dist/errors/IconError.js:19:108)
    at Jimp.<anonymous> (/scrapdviz/node_modules/webpack-pwa-manifest/dist/icons/index.js:128:22)
    at Jimp.throwError (/scrapdviz/node_modules/jimp/index.js:85:44)
    at ReadFileContext.callback (/scrapdviz/node_modules/jimp/index.js:201:44)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:242:13)
```

**Comment by rgreinho** [comment]
The manifest in `next.config.js` is completely wrong as it is a copy/paste from a previous project. It needs to be update to allow building the application.
